#!/bin/bash

# CONSTANT
contest="abc"

if [ $# == 0 ]; then
    echo "please input test number."
    exit

elif [ $# = 1 ]; then
    START=$1
    END=${START}

elif [ $# = 2 ]; then
    START=$1
    END=$2
fi
    
for ((NUM=${START} ; NUM<=${END} ; NUM++)); do
rm -rf ./${NUM}
mkdir ./${NUM}
for level in A B C D; do
mkdir ./${NUM}/${level^}
cp ./template/main.cpp ./${NUM}/${level^}
done

for level in a b c d; do
cd ./${NUM}/${level^}
    URL="https://atcoder.jp/contests/"${contest}${NUM}"/tasks/"${contest}${NUM}"_"${level}
oj dl ${URL}
cd -
done
done
